BonTemps/Controllers/ChefController.cs
using BonTemps.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;

namespace BonTemps.Controllers
{
    [Authorize(Roles = "kok,Admin")]
    public class ChefController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Chef
        public ActionResult Index()
        {
            var first = DateTime.Now.AddHours(-2);
            var last = DateTime.Now.AddHours(2);
            var orders = db.Orders.Include(o => o.Menu).Include(o => o.Reservation).Include(o => o.Reservation.Customer).Where(o => o.Reservation.Date > first && o.Reservation.Date < last).ToList();
            return View(orders);
        }
    }
}

BonTemps/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BonTemps.Models;
using DocumentFormat.OpenXml.Bibliography;

namespace BonTemps.Controllers
{
    [Authorize(Roles = "kok,Admin")]
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Menus
        public ActionResult Index()
        {
            return View(db.Menus.ToList());
        }

        // GET: Menus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menus menus = db.Menus.Find(id);
            if (menus == null)
            {
                return HttpNotFound();
            }
            return View(menus);
        }

        // GET: Menus/Create
        public ActionResult Create()
        {
            ViewBag.allergies = db.Allergies.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(allergyMenuViewModel allergyMenuViewModel, HttpPostedFileBase picture)
        {
            var menu = new Menus { DateCreated = DateTime.Now, Description = allergyMenuViewModel.Description, Name = allergyMenuViewModel.Name };
            ViewBag.allergies = db.Allergies.ToList();

            if (picture == null)
            {
                TempData["warning"] = "Geen afbeelding geupload";
                return View(allergyMenuViewModel);
            }

            menu.Image = UploadImage(picture);

            db.Menus.Add(menu);
            db.SaveChanges();

            if (allergyMenuViewModel.Allergies.StartsWith(","))
            {
                allergyMenuViewModel.Allergies = allergyMenuViewModel.Allergies.Substring(1);
            }

            foreach (var allergy in allergyMenuViewModel.Allergies.Split(','))
            {
                var intAllergy = Convert.ToInt16(allergy);
                var allergyObj = new Menus_Allergies
                {
                    Allergie = db.Allergies.FirstOrDefault(a => a.Id == intAllergy),
                    Menu = menu
                };

                db.Menus_Allergies.Add(allergyObj);
            }

            db.SaveChanges();
            TempData["success"] = "Sucesvol opgeslagen";
            return View();
        }

        // GET: Menus/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.allergies = db.Allergies.ToList();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menus menus = db.Menus.Find(id);
            if (menus == null)
            {
                return HttpNotFound();
            }

            var arr = db.Menus_Allergies.Where(m => m.Menu.Id == menus.Id).Select(m => m.Allergie).Select(m => m.Id);

            var allergies = string.Join(",", arr);

            var modelview = new allergyMenuViewModel
            {
                Description = menus.Description,
                Name = menus.Name,
                Allergies = allergies
            };
            return View(modelview);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(allergyMenuViewModel allergyMenuViewModel, HttpPostedFileBase picture)
        {
            ViewBag.allergies = db.Allergies.ToList();

            if (string.IsNullOrEmpty(allergyMenuViewModel.Name) || string.IsNullOrEmpty(allergyMenuViewModel.Description))
            {
                TempData["error"] = "Ongeldige waardes";
                return View(allergyMenuViewModel);
            }

            var menu = new Menus { DateCreated = DateTime.Now, Description = allergyMenuViewModel.Description, Name = allergyMenuViewModel.Name };
            ViewBag.allergies = db.Allergies.ToList();

            if (!ModelState.IsValid)
                return View(allergyMenuViewModel);

            if (picture != null)
            {
                menu.Image = UploadImage(picture);
            }

            db.Entry(menu).State = EntityState.Modified;

            if (picture == null)
            {
                db.Entry(menu).Property(x => x.Image).IsModified = false;
            }

            db.Menus_Allergies.RemoveRange(db.Menus_Allergies.Where(m => m.Menu.Id == menu.Id));

            if (allergyMenuViewModel.Allergies.StartsWith(","))
            {
                allergyMenuViewModel.Allergies = allergyMenuViewModel.Allergies.Substring(1);
            }

            foreach (var allergy in allergyMenuViewModel.Allergies.Split(','))
            {
                var intAllergy = Convert.ToInt16(allergy);
                var allergyObj = new Menus_Allergies
                {
                    Allergie = db.Allergies.FirstOrDefault(a => a.Id == intAllergy),
                    Menu = menu
                };

                db.Menus_Allergies.Add(allergyObj);
            }

            db.SaveChanges();
            TempData["success"] = "Sucesvol opgeslagen";
            return View();
        }

        // GET: Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menus menus = db.Menus.Find(id);
            if (menus == null)
            {
                return HttpNotFound();
            }
            return View(menus);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menus menus = db.Menus.Find(id);
            db.Menus.Remove(menus);
            db.SaveChanges();
            TempData["success"] = "Succesvol verwijderd";
            return RedirectToAction("Index");
        }

        public string UploadImage(HttpPostedFileBase image)
        {
            var uploadPath = Server.MapPath("~/Content/Uploads/menu-images");
            Directory.CreateDirectory(uploadPath);
            var fileGuid = Guid.NewGuid().ToString();
            var extension = Path.GetExtension(image.FileName);
            var newFilename = fileGuid + extension;
            image.SaveAs(Path.Combine(uploadPath, newFilename));
            return newFilename;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BonTemps/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BonTemps.Models;

namespace BonTemps.Controllers
{
    [Authorize(Roles = "Admin,Serveerster")]
    public class OrderController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Menus
        public ActionResult Index()
        {
            return View(db.Orders.Include(o => o.Reservation).Include(o => o.Reservation.Customer).Include(o => o.Menu).ToList());
        }

        // GET: Menus/Create
        public ActionResult Create(int? reservationId)
        {
            var minusTwoHours = DateTime.Now.AddHours(-2);
            ViewBag.reservations = db.Reservations.Include(r => r.Customer).Where(r => r.Date > minusTwoHours).ToList();
            ViewBag.reservationId = reservationId;
            ViewBag.menus = db.Menus.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(string menus, int? reservationId)
        {
            ViewBag.menus = db.Menus.ToList();
            var minusTwoHours = DateTime.Now.AddHours(-2);
            ViewBag.reservations = db.Reservations.Include(r => r.Customer).Where(r => r.Date > minusTwoHours).ToList();

            if (reservationId == null || reservationId == 0)
            {
                ViewBag.reservationId = reservationId;
                TempData["error"] = "ReserveringId is leeg";
                return View();
            }
            ViewBag.menus = db.Menus.ToList();
            
            if (menus.StartsWith(","))
            {
                menus = menus.Substring(1);
            }

            foreach (var menu in menus.Split(','))
            {
                var intMenu = Convert.ToInt16(menu);
                var orderObj = new Orders
                {
                    Menu = db.Menus.FirstOrDefault(a => a.Id == intMenu),
                    Reservation = db.Reservations.FirstOrDefault(a => a.Id == reservationId)
                };

                db.Orders.Add(orderObj);
            }

            db.SaveChanges();
            TempData["success"] = "Sucesvol aangemaakt";
            return View();
        }

        // GET: Menus/Create
        public ActionResult Edit(int? id)
        {
            ViewBag.reservationId = id;
            var arr = db.Orders.Where(m => m.Reservation.Id == id).Select(m => m.Menu).Select(m => m.Id);
            ViewBag.menuArr = string.Join(",", arr);

            var minusTwoHours = DateTime.Now.AddHours(-2);
            ViewBag.reservations = db.Reservations.Include(r => r.Customer).Where(r => r.Date > minusTwoHours).ToList();
            ViewBag.menus = db.Menus.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Edit(string menus, int? reservationId)
        {
            ViewBag.reservationId = reservationId;
            ViewBag.menus = db.Menus.ToList();
            var minusTwoHours = DateTime.Now.AddHours(-2);
            ViewBag.reservations = db.Reservations.Include(r => r.Customer).Where(r => r.Date > minusTwoHours).ToList();

            if (reservationId == null || reservationId == 0)
            {
                ViewBag.reservationId = reservationId;
                TempData["error"] = "ReserveringId is leeg";
                return View();
            }
            ViewBag.menus = db.Menus.ToList();

            if (menus.StartsWith(","))
            {
                menus = menus.Substring(1);
            }

            db.Orders.RemoveRange(db.Orders.Where(m => m.Reservation.Id == reservationId));

            foreach (var menu in menus.Split(','))
            {
                var intMenu = Convert.ToInt16(menu);
                var orderObj = new Orders
                {
                    Menu = db.Menus.FirstOrDefault(a => a.Id == intMenu),
                    Reservation = db.Reservations.FirstOrDefault(a => a.Id == reservationId)
                };

                db.Orders.Add(orderObj);
            }

            db.SaveChanges();
            TempData["success"] = "Sucesvol opgeslagen";

            var arr = db.Orders.Where(m => m.Reservation.Id == reservationId).Select(m => m.Menu).Select(m => m.Id);
            ViewBag.menuArr = string.Join(",", arr);

            return View();
        }


        // GET: Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menus menus = db.Menus.Find(id);
            if (menus == null)
            {
                return HttpNotFound();
            }
            return View(menus);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menus menus = db.Menus.Find(id);
            db.Menus.Remove(menus);
            db.SaveChanges();
            TempData["success"] = "Succesvol verwijderd";
            return RedirectToAction("Index");
        }
        }
}

BonTemps/Views/Shared/Internal.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>500 - Internal Server Error</title>
</head>
<body>
    <div class="error">
        <div class="error-code m-b-10 m-t-20">404 <i class="fa fa-warning"></i></div>
        <h3 class="font-bold">Er ging iets fout!</h3>
        <div class="error-desc">
            Sorry, er ging iets fout in de applicatie! <br />
            Probeer de pagina te refreshen of klik op de knop hieronder om terug te gaan naar de homepagina.
            <div>
                <div class=" login-detail-panel-button btn" href="">
                    <a href="@Url.Action("Index", "Home")">Ga terug</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

BonTemps/Views/Shared/NotFound.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>404 - Not Found</title>
</head>
<body>
    <div class="error">
        <div class="error-code m-b-10 m-t-20">404 <i class="fa fa-warning"></i></div>
        <h3 class="font-bold">We couldn't find the page..</h3>
        <div class="error-desc">
            Sorry, de pagina waar je naar zoekt is niet gevonden.<br />
            Probeer de pagina te refreshen of klik op de knop hieronder om terug te gaan naar de homepagina.
            <div>
                <div class=" login-detail-panel-button btn" href="">
                    <a href="@Url.Action("Index", "Home")">Ga terug</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

BonTemps/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="description" content="Miminium Admin Template v.1">
    <meta name="author" content="Isna Nur Azis">
    <meta name="keyword" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bon Temps Intranet</title>

    @Styles.Render("~/Content/defaultcss")

    <!-- end: Css -->

    <link rel="shortcut icon" href="asset/img/logomi.png">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="mimin" class="dashboard">
    <!-- start: Header -->
    <nav class="navbar navbar-default header navbar-fixed-top">
        <div class="col-md-12 nav-wrapper">
            <div class="navbar-header" style="width:100%;">
                <a href="/" class="navbar-brand">
                    <b>Bon Temps</b>
                </a>
                <ul class="nav navbar-nav navbar-right user-nav" style="position:fixed; right:40px;">
                    <li class="user-name">
                        <span>
                            @if (Session["roles"] != null)
                            {
                                foreach (var role in (List<string>)Session["roles"])
                                {<span>@role </span> }
                             }
                        else
                        { <span>Gebruiker</span>}
                        </span>
                    </li>
                    <li class="dropdown avatar-dropdown">
                        <img onclick="window.location = '@Url.Action("LogOut", "Account")';" src="http://www.pvhc.net/img162/kzkdpyqytlhncwjrpvzf.png" style="height: 30px; width: 30px; margin-top: 40%; cursor: pointer;" alt="" />
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- end: Header -->

    <div class="container-fluid mimin-wrapper">

        <!-- start:Left Menu -->
        <div id="left-menu">
            <div class="sub-left-menu scroll">
                <ul class="nav nav-list">
                    <!--<li><div class="left-bg"></div></li>-->
                    <img src="~/asset/img/logoBonTemps.png" width="150px" class="animated fadeInLeft" height="150px" alt="logo" style="margin-left: 35px; margin-bottom:5px; margin-top: 10%;">
                    <hr>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Serveerster"))
                    {
                    <li class="active ripple">
                        <a class="tree-toggle nav-header">
                            Reserveren
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="@Url.Action("Create", "Reservation")">Aanmaken</a></li>
                            <li><a href="@Url.Action("Index", "Reservation")">Overzicht</a></li>
                        </ul>
                    </li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("kok"))
                    {
                        <li class="active ripple">
                            <a class="tree-toggle nav-header">
                                Keuken
                                <span class="fa-angle-right fa right-arrow text-right"></span>
                            </a>
                            <ul class="nav nav-list tree">
                                <li>
                                    <a href="@Url.Action("Index", "Chef")">Overzicht</a>
                                </li>
                            </ul>
                        </li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("kok"))
                    {
                    <li class="active ripple">
                        <a class="tree-toggle nav-header">
                            Menu's
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="@Url.Action("Create", "Menu")">Aanmaken</a></li>
                            <li><a href="@Url.Action("Index", "Menu")">Overzicht</a></li>
                        </ul>
                    </li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("kok"))
                    {
                    <li class="active ripple">
                        <a class="tree-toggle nav-header">
                            Allergieën
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li>
                                <a href="@Url.Action("Create", "Allergies")">Aanmaken</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "Allergies")">Overzicht</a>
                            </li>
                        </ul>
                    </li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Serveerster"))
                    {
                        <li class="active ripple">
                            <a class="tree-toggle nav-header">
                                Bestellingen
                                <span class="fa-angle-right fa right-arrow text-right"></span>
                            </a>
                            <ul class="nav nav-list tree">
                                <li><a href="@Url.Action("Index", "Order")">Overzicht</a></li>
                                <li><a href="@Url.Action("Edit", "Order")">Wijzigen</a></li>
                            </ul>
                        </li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Serveerster"))
                    { 
                    <li class="active ripple">
                        <a class="tree-toggle nav-header">
                            Tafel Overzicht
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="@Url.Action("Index", "Table_layout")">Overzicht</a></li>
                            <li><a href="@Url.Action("Edit", "Table_layout")">Wijzigen</a></li>
                        </ul>
                    </li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                    <li class="active ripple">
                        <a class="tree-toggle nav-header">
                            Klant overzicht
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="@Url.Action("Index", "Customers")">Overzicht</a></li>
                        </ul>
                    </li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                    <li class="active ripple">
                        <a class="tree-toggle nav-header">
                            Account Overzicht
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="@Url.Action("Index", "Role_Manage")">Overzicht</a></li>
                        </ul>
                    </li>
                    }
                </ul>
            </div>
        </div>
        <!-- end: Left Menu -->
        <!-- start: content -->
        <div id="content">
            <br />
            <div class="container">

                @if (TempData["messageSuccess"] != null)
                {
                    <div class="alert alert-success fade in">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <span class="glyphicon glyphicon-info-sign"></span> @TempData["messageSuccess"]
                    </div>
                }
                @if (TempData["messageWarning"] != null)
                {
                    <div class="alert alert-warning fade in">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <span class="glyphicon glyphicon-warning-sign"></span> @TempData["messageWarning"]
                    </div>
                }
                @if (TempData["messageError"] != null)
                {
                    <div class="alert alert-danger fade in">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <span class="glyphicon glyphicon-exclamation-sign"></span> @TempData["messageError"]
                    </div>
                }
                @if (TempData["messageInfo"] != null)
                {
                    <div class="alert alert-info fade in">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <span class="glyphicon glyphicon-info-sign"></span> @TempData["messageInfo"]
                    </div>
                }
            </div>
            <div style="margin-top: 30px !important;">
            @RenderBody()
                </div>
        </div>
        <!-- end: content -->


    </div>

    <!-- start: Mobile -->
    <button id="mimin-mobile-menu-opener" class="animated rubberBand btn btn-circle btn-danger">
        <span class="fa fa-bars"></span>
    </button>
    <!-- end: Mobile -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/defaultscripts")
    @RenderSection("Scripts", false)

    <!-- alerts-->
    <script>
    @{
        if (TempData["error"] != null)
        {
            <text>alertify.error('@TempData["error"]');</text>
        }
        if (TempData["warning"] != null)
        {
            <text>alertify.warning('@TempData["warning"]');</text>
        }
        if (TempData["success"] != null)
        {
            <text>alertify.success('@TempData["success"]');</text>
        }
        if (TempData["message"] != null)
        {
            <text>alertify.message('@TempData["message"]');</text>
        }
       }
    </script>

    <!-- custom -->
    <script type="text/javascript">
        (function () {
            $('.date-fr').bootstrapMaterialDatePicker({ format: 'DD-MM-YYYY HH:mm:ss', animation: true, lang: 'nl', weekStart: 1, cancelText: 'Annuleer' });
            $('.date-fr').removeAttr("data-val-date");
            $('.birth-date').removeAttr("data-val-date");
        })(jQuery);
    </script>
    <!-- end: Javascript -->
</body>
</html>